Make MonsterActivityComponent Partial for extensions Fix errors: DefaultGameSaveSystem.cs(29,87): error CS0103: The name 'FindObjectsSortMode' does not exist in the current context DefaultGameSaveSystem.cs(29,53): error CS0103: The name 'FindObjectsByType'